### ISSUE TITLE
Concern with GUAVA

### ISSUE THREAD

**Issue by Zahid11** [MayurDivate/GUAVASourceCode#16]
Hi,
am trying to analyze my ATAC Seq data. I ran successfully build the genomw index, but when I tried to start analysis program, it gives following error.

Please help what should I do?
Thank you,
Zahid

		cutadapt:		Working!
		bowtie:		Working!
		bowtie2:	Working!
		fastqc:		Working!
		samtools:	Working!
		MACS2 version (macs2 2.1.1.20160309) :			NOT FOUND !!!
		Picard:		Working!
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!

There are missing dependancies!
Please use configure.sh to install dependencies.
If you are having difficulties in installing dependencies, please report issue at *GitHub*.
>>> https://github.com/MayurDivate/GUAVASourceCode/issues
EXIT(GUAVA) ... 
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ pip install MACS2==2.1.1.20160309
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting MACS2==2.1.1.20160309
  Downloading https://files.pythonhosted.org/packages/9f/99/a8ac96b357f6b0a6f559fe0f5a81bcae12b98579551620ce07c5183aee2c/MACS2-2.1.1.20160309.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 4.4MB/s 
Requirement already satisfied: numpy>=1.6 in /Users/zahidakhter/miniconda2/lib/python2.7

/site-packages (from MACS2==2.1.1.20160309) (1.16.3)
Building wheels for collected packages: MACS2
  Building wheel for MACS2 (setup.py) ... done
  Stored in directory: /Users/zahidakhter/Library/Caches/pip/wheels/93/d9/92/46e5099384e50bfb1be6cea3c692ee7c5ef3e60fbc7b4f7ef1
Successfully built MACS2
Installing collected packages: MACS2
  Found existing installation: MACS2 2.1.2
    Uninstalling MACS2-2.1.2:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/MACS2-2.1.2.dist-info/RECORD'
Consider using the `--user` option or check the permissions.

(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$

**Comment by MayurDivate** [comment]
Hi, This issue has been already addressed here [MACS2](https://github.com/MayurDivate/GUAVASourceCode/issues/3#issuecomment-438342315).

Mayur

**Comment by Zahid11** [comment]
Hi Mayur,

Thanks for your response.
 Although, I installed dependencies, I get the following comment on my
terminal.

What can I do? Please help.

Best,
Zahid


Operating System of machine :Mac OS X
cutadapt: Working!
bowtie: Working!
bowtie2: Working!
fastqc: Working!
samtools: Working!
Cannot run program "macs2": error=2, No such file or directory
MACS2 version (macs2 2.1.1.20160309) : NOT FOUND !!!
Picard: Working!
bedtools: Working!
bedGraphToBigWig: Working!
igv: Working!

There are missing dependancies!
Please use configure.sh to install dependencies.
If you are having difficulties in installing dependencies, please report
issue at *GitHub*.
>>> https://github.com/MayurDivate/GUAVASourceCode/issues

**Comment by Zahid11** [comment]
Hi Mayur,

My system has macs2 (2.1.2). Hence, I entered command as follow to remove it. I got the following error. Please help.

Thanks,



(base) Zahids-MacBook-Air:~ zahidakhter$ pip uninstall macs2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Uninstalling MACS2-2.1.2:
  Would remove:
    /Users/zahidakhter/miniconda2/lib/python2.7/site-packages/MACS2-2.1.2.dist-info/*
    /Users/zahidakhter/miniconda2/lib/python2.7/site-packages/MACS2/*
Proceed (y/n)? y
Exception:
Traceback (most recent call last):
  File "/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/pip/_internal/commands/uninstall.py", line 75, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 817, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/pip/_internal/req/req_uninstall.py", line 360, in remove
    moved.stash(path)
  File "/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/pip/_internal/req/req_uninstall.py", line 257, in stash
    renames(path, new_path)
  File "/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 303, in renames
    shutil.move(old, new)
  File "/Users/zahidakhter/miniconda2/lib/python2.7/shutil.py", line 323, in move
    rmtree(src)
  File "/Users/zahidakhter/miniconda2/lib/python2.7/shutil.py", line 275, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/Users/zahidakhter/miniconda2/lib/python2.7/shutil.py", line 273, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/MACS2-2.1.2.dist-info/RECORD'

**Comment by MayurDivate** [comment]
Do you mean that manual MACS2 installation using pip did not override 2.1.2 version?
Let me know the output of the following commands, 
```macs2 --version```
```which macs2```

Error message says you have permission issue. 

Try using user which has sufficient rights.

Thanks,
Mayur

**Comment by Zahid11** [comment]
Hi Mayur,

Sorry to bother you again. Yes, it did not override 2.1.2 version. The output of the above command is:

(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ macs2 --version
-bash: macs2: command not found
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ which macs2
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ 

What should I do now?? Thank you for your consistent help.

Thanks much,
Zahid

**Comment by Zahid11** [comment]
Hi Mayur,

Sorry to bother you again. Yes, it did not override 2.1.2 version. The
output of the above command is:

(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ macs2 --version
-bash: macs2: command not found
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ which macs2
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$

What should I do now?? Thank you for your consistent help.

Thanks much,
Zahid

**Comment by MayurDivate** [comment]
Above output confirms that there is no MACS2 installed.
Please run following command to install MACS2
```pip install MACS2==2.1.1.20160309```
 
Once it is successfully installed, run above commands again to verify.

Thanks,
Mayur

**Comment by Zahid11** [comment]
When I ran the above command, output as follows: Where it went wrong? Thank
you

(base) Zahids-MacBook-Air:~ zahidakhter$ pip install MACS2==2.1.1.20160309
DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Please upgrade your Python as Python 2.7 won't be maintained after
that date. A future version of pip will drop support for Python 2.7.
Collecting MACS2==2.1.1.20160309
Requirement already satisfied: numpy>=1.6 in
./miniconda2/lib/python2.7/site-packages (from MACS2==2.1.1.20160309)
(1.16.3)
Installing collected packages: MACS2
  Found existing installation: MACS2 2.1.2
    Uninstalling MACS2-2.1.2:
Could not install packages due to an EnvironmentError: [Errno 13]
Permission denied:
'/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/MACS2-2.1.2.dist-info/RECORD'
Consider using the `--user` option or check the permissions.

**Comment by Zahid11** [comment]
When I ran the above command, output as follows: Where it went wrong? Thank you

(base) Zahids-MacBook-Air:~ zahidakhter$ pip install MACS2==2.1.1.20160309
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting MACS2==2.1.1.20160309
Requirement already satisfied: numpy>=1.6 in ./miniconda2/lib/python2.7/site-packages (from MACS2==2.1.1.20160309) (1.16.3)
Installing collected packages: MACS2
  Found existing installation: MACS2 2.1.2
    Uninstalling MACS2-2.1.2:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Users/zahidakhter/miniconda2/lib/python2.7/site-packages/MACS2-2.1.2.dist-info/RECORD'
Consider using the `--user` option or check the permissions.

**Comment by MayurDivate** [comment]
Try following command
```pip install --user MACS2==2.1.1.20160309```

If above fails, then try the one below,
``` sudo pip install MACS2==2.1.1.20160309```

The later one will ask password.
One of the should fix your problem.

Thanks,
Mayur

**Comment by Zahid11** [comment]
Above first command successfully installed MACS2. When I rerun the command,
out put is:

(base) Zahids-MacBook-Air:~ zahidakhter$ pip install --user
MACS2==2.1.1.20160309
DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Please upgrade your Python as Python 2.7 won't be maintained after
that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: MACS2==2.1.1.20160309 in
./.local/lib/python2.7/site-packages (2.1.1.20160309)
Requirement already satisfied: numpy>=1.6 in
./miniconda2/lib/python2.7/site-packages (from MACS2==2.1.1.20160309)
(1.16.3)
(base) Zahids-MacBook-Air:~ zahidakhter$

But, when I begin ATAC Seq data analysis, out put is as below, although I
ran dependencies using command sh ./configure.sh

(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ java -jar GUAVA.jar
GUAVA version 1
Operating System of machine :Mac OS X
cutadapt: Working!
bowtie: Working!
bowtie2: Working!
fastqc: Working!
samtools: Working!
Cannot run program "macs2": error=2, No such file or directory
MACS2 version (macs2 2.1.1.20160309) : NOT FOUND !!!
Picard: Working!
bedtools: Working!
bedGraphToBigWig: Working!
igv: Working!

There are missing dependancies!
Please use configure.sh to install dependencies.
If you are having difficulties in installing dependencies, please report
issue at *GitHub*.
>>> https://github.com/MayurDivate/GUAVASourceCode/issues
EXIT(GUAVA) ...
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$


What went wrong? In fact, I want use GUAVA for my ATAC seq data, but I am
stuck. I thank you for your help and support.

Thank you,

**Comment by MayurDivate** [comment]
No, It did not install MACS2.
From the error message it is apparent that old MACS2 installation is present on the system.
However, that is now working. 

Completely uninstall or remove MACS2 installation via **conda**.
Then try installing fresh MACS2 as discussed earlier.

To delete macs2 from site-packages, use following command.
`rm -rf ~/.local/lib/python2.7/site-packages/MACS2`

Mayur

**Comment by Zahid11** [comment]
I think the above command to uninstall MACS2 didn't uninstall. I tried and got below out put.

(base) Zahids-MacBook-Air:~ zahidakhter$ rm -rf ~/.local/lib/python2.7/site-packages/MACS2
(base) Zahids-MacBook-Air:~ zahidakhter$ 
(base) Zahids-MacBook-Air:~ zahidakhter$ cd ~/GUAVA-1
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ rm -rf ~/.local/lib/python2.7/site-packages/MACS2
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ 

What's your opinion about it? any other command to uninstall MACS2??
I really appreciate your help.

Thanks,
Zahid

**Comment by Zahid11** [comment]
I think the above command to uninstall MACS2 didn't uninstall. I tried and
got below out put.

(base) Zahids-MacBook-Air:~ zahidakhter$ rm -rf
~/.local/lib/python2.7/site-packages/MACS2
(base) Zahids-MacBook-Air:~ zahidakhter$
(base) Zahids-MacBook-Air:~ zahidakhter$ cd ~/GUAVA-1
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ rm -rf
~/.local/lib/python2.7/site-packages/MACS2
(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$

What's your opinion about it? any other command to uninstall MACS2??
I really appreciate your help.

Thanks,
Zahid

**Comment by MayurDivate** [comment]
Yes exactly ! 

I want you to remove old installations first.
After that, install fresh one.

cheers,
Mayur

**Comment by Zahid11** [comment]
I tried to remove old macs2 using the command rm -rf
~/.local/lib/python2.7/site-packages/MACS2.
But, it gives out put as below: Does it mean the old macs2 is removed? Even
I followed up and install fresh macs2 afterward, and proceeded with the
ATAC seq data analysis, I found it again macs2 not found.

(base) Zahids-MacBook-Air:~ zahidakhter$ rm -rf
~/.local/lib/python2.7/site-packages/MACS2
(base) Zahids-MacBook-Air:~ zahidakhter$


Thank u

**Comment by MayurDivate** [comment]
Run following commands one by one and let me know the outputs.

`macs2 --version`
`which macs2`
`ls ~/.local/lib/python2.7/site-packages/MACS2*`

Mayur

**Comment by Zahid11** [comment]
Below is out put after running above commands:

Last login: Mon May 27 19:23:43 on ttys000
(base) Zahids-MacBook-Air:~ zahidakhter$ macs2 --version
-bash: macs2: command not found
(base) Zahids-MacBook-Air:~ zahidakhter$ which macs2
(base) Zahids-MacBook-Air:~ zahidakhter$ ls
~/.local/lib/python2.7/site-packages/MACS2*
COPYING METADATA WHEEL
INSTALLER RECORD top_level.txt
(base) Zahids-MacBook-Air:~ zahidakhter$

**Comment by MayurDivate** [comment]
Looks like, you are good to go for the fresh installation of MACS2. 
For the instructions, please refer my previous [comment](https://github.com/MayurDivate/GUAVASourceCode/issues/16#issuecomment-496072861)

Mayur

**Comment by Zahid11** [comment]
I tried both the commands above to install fresh MACS2. However, when I run
ATAC Seq data analysis, the out put pops up as below (seems still MACS2
didn't install):

Please advise. Thank you,

(base) Zahids-MacBook-Air:GUAVA-1 zahidakhter$ java -jar GUAVA.jar
GUAVA version 1
Operating System of machine :Mac OS X
cutadapt: Working!
bowtie: Working!
bowtie2: Working!
fastqc: Working!
samtools: Working!
Cannot run program "macs2": error=2, No such file or directory
*MACS2 version (macs2 2.1.1.20160309) : NOT FOUND !!!*
Picard: Working!
bedtools: Working!
bedGraphToBigWig: Working!
igv: Working!

There are missing dependancies!
Please use configure.sh to install dependencies.
If you are having difficulties in installing dependencies, please report
issue at *GitHub*.
>>> https://github.com/MayurDivate/GUAVASourceCode/issues

**Comment by MayurDivate** [comment]
Hi,

To get GUAVA working, you will need MACS2 version 2.1.1.20160309.

How to check current macs2 version?
`macs2 --version`

If above command produces output **`macs2: command not found`.**
_That means you haven't yet installed macs2 successfully._

**To install macs2 refer previous [comment]**(https://github.com/MayurDivate/GUAVASourceCode/issues/16#issuecomment-496072861)

So far this worked for all users who experienced same issue.
If you still have difficulties in installing macs2, please share specific error messages.

All the best,
Mayur

**Comment by Zahid11** [comment]
I used both the commands to install MACS2. Please see below,

(i) The message using command pip install --user MACS2==2.1.1.20160309
is below:

Last login: Tue May 28 17:46:05 on ttys000
(base) Zahids-MacBook-Air:~ zahidakhter$ pip install --user
MACS2==2.1.1.20160309
DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Please upgrade your Python as Python 2.7 won't be maintained after
that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: MACS2==2.1.1.20160309 in
./.local/lib/python2.7/site-packages (2.1.1.20160309)
Requirement already satisfied: numpy>=1.6 in
./miniconda2/lib/python2.7/site-packages (from MACS2==2.1.1.20160309)
(1.16.3)


(ii) The message using command sudo pip install MACS2==2.1.1.20160309
is below:

Last login: Tue May 28 21:12:54 on ttys000
(base) Zahids-MacBook-Air:~ zahidakhter$ sudo pip install
MACS2==2.1.1.20160309
Password:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st,
2020. Please upgrade your Python as Python 2.7 won't be maintained after
that date. A future version of pip will drop support for Python 2.7.
The directory '/Users/zahidakhter/Library/Caches/pip/http' or its parent
directory is not owned by the current user and the cache has been disabled.
Please check the permissions and owner of that directory. If executing pip
with sudo, you may want sudo's -H flag.
The directory '/Users/zahidakhter/Library/Caches/pip' or its parent
directory is not owned by the current user and caching wheels has been
disabled. check the permissions and owner of that directory. If executing
pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: MACS2==2.1.1.20160309 in
./.local/lib/python2.7/site-packages (2.1.1.20160309)
Requirement already satisfied: numpy>=1.6 in
./miniconda2/lib/python2.7/site-packages (from MACS2==2.1.1.20160309)
(1.16.3)

Please advise.
Thanks

**Comment by MayurDivate** [comment]
Have you tried this command `macs2 --version` as mentioned above to check macs2 installation ?

**Comment by Zahid11** [comment]
Hi Mayur,

Yes I did. It gives out put as below: Seems like both of the above commands
pertaining to install MACS2 didn't work. What went wrong? Your advise
please?? Thanks

(base) Zahids-MacBook-Air:~ zahidakhter$ macs2 --version
-bash: macs2: command not found
(base) Zahids-MacBook-Air:~ zahidakhter$

**Comment by Zahid11** [comment]
Hi Mayur,
Please advise me, how should I go ahead from here??

Thanks,

**Comment by MayurDivate** [comment]
> Hi Mayur, Yes I did. It gives out put as below: Seems like both of the above commands pertaining to install MACS2 didn't work. What went wrong? Your advise please?? Thanks (base) Zahids-MacBook-Air:~ zahidakhter$ macs2 --version -bash: macs2: command not found (base) Zahids-MacBook-Air:~ zahidakhter$
> […](#)

"-bash: macs2: command not found"
This means, macs2 is missing. 
You have to install it first.
Check previous comments for macs2 installation instructions.
