### ISSUE TITLE
Picard does not find files or directory

### ISSUE THREAD

**Issue by MargheritaSq** [MayurDivate/GUAVASourceCode#30]
Hi!

I am following the GUAVA manual analyzing the Sample Data (DMSO_Rep1_R1.fastq and DMSO_Rep1_R2.fastq) and everything worked perfectly fine until the Picard step.
In my output folder I have the Adpater and Fastqc results but after bowtie2 finished to work I did not get and bowtie directory containing its results. I do not know if it is ok or not. Anyway for the analysis I considerd hg19 as reference genome and only chrM, as described in the manual. I had left all the other parameter sto the default values.
Could you help me?

Thanks!

Down here I report GUAVA complete output:

(GUAVAenvpy2.7) MargherariosAir:GUAVA-1 margheritas$ java -jar GUAVA.jar 
GUAVA version 1
Operating System of machine :Mac OS X
		cutadapt:		Working!
		bowtie:		Working!
		bowtie2:	Working!
		fastqc:		Working!
		samtools:	Working!
		macs2:		Working!
		Picard:		Working!
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!
Adapter trimming...Done
fastq QC...
Alignment...
Please wait while bowtie2 alignment is finished..Done!
---- Alignment filtering ------
Remove duplicates...		Cannot run program "picard" (in directory "/Users/margheritas/MyPythonEnv/GUAVA-1/Result_sample_data_DMSO_rep1/DMSO_Rep1_R1_OUTPUT"): error=2, No such file or directory
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at umac.guava.Tool.writeLog(Tool.java:89)
	at umac.guava.AnalysisWorkflow.getDuplicateFilteredBAM(AnalysisWorkflow.java:707)
	at umac.guava.AnalysisWorkflow.runAlignmentFiltering(AnalysisWorkflow.java:556)
	at umac.guava.AnalysisWorkflow.startGUIGuavaAnalysis(AnalysisWorkflow.java:166)
	at umac.guava.MainJFrame.startJButtonActionPerformed(MainJFrame.java:837)
	at umac.guava.MainJFrame.access$700(MainJFrame.java:27)
	at umac.guava.MainJFrame$8.actionPerformed(MainJFrame.java:267)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by MayurDivate** [comment]
Dear @MargheritaSq 

```
"I considerd hg19 as reference genome and only chrM"
```
For alignment of sample data, you must include chromosomes other than ChrM.
ChrM filtering is optional.

Mayur

**Comment by MargheritaSq** [comment]
Thank you very much! Now it works.
